version: '3.4'

services:
  backend:
    image: stack-backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes: 
      - type: bind
        source: ./backend
        target: /app
    environment: 
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - BACKEND_DATABASE_CONNECTION_STRING=${BACKEND_DATABASE_CONNECTION_STRING}
  database:
    image: postgres:12-alpine
    environment: 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes: 
      - type: bind
        source: ./database/data
        target: /var/lib/postgresql/data/pgdata
